#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# generated by wxGlade 0.6.6 on Thu Mar 13 19:18:27 2014
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class AdonsTree(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AdonsTree.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.tree_ctrl_1 = wx.TreeCtrl(self, wx.ID_ANY, style=wx.TR_HAS_BUTTONS | wx.TR_NO_LINES | wx.TR_FULL_ROW_HIGHLIGHT | wx.TR_DEFAULT_STYLE | wx.SUNKEN_BORDER)
        self.btnEnable = wx.Button(self, wx.ID_ANY, u"Подключить")
        self.btnDisable = wx.Button(self, wx.ID_ANY, u"Отключить")
        self.btnOk = wx.Button(self, wx.ID_ANY, u"ОК")
        self.btnCancel = wx.Button(self, wx.ID_ANY, u"Отмена")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btnEnable_handler, self.btnEnable)
        self.Bind(wx.EVT_BUTTON, self.btnDisable_handler, self.btnDisable)
        self.Bind(wx.EVT_BUTTON, self.btnOk_handler, self.btnOk)
        self.Bind(wx.EVT_BUTTON, self.btnCancel_handler, self.btnCancel)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AdonsTree.__set_properties
        self.SetTitle(u"Подключаемые модули")
        self.tree_ctrl_1.SetMinSize((331, 379))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AdonsTree.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.FlexGridSizer(2, 1, 0, 0)
        sizer_4 = wx.GridSizer(1, 4, 0, 0)
        sizer_3.Add(self.tree_ctrl_1, 1, wx.EXPAND | wx.FIXED_MINSIZE, 0)
        sizer_4.Add(self.btnEnable, 0, wx.EXPAND | wx.FIXED_MINSIZE, 0)
        sizer_4.Add(self.btnDisable, 0, wx.EXPAND | wx.FIXED_MINSIZE, 0)
        sizer_4.Add(self.btnOk, 0, wx.EXPAND, 0)
        sizer_4.Add(self.btnCancel, 0, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3.AddGrowableRow(0)
        sizer_3.AddGrowableCol(0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

    def btnEnable_handler(self, event):  # wxGlade: AdonsTree.<event_handler>
        print "Event handler 'btnEnable_handler' not implemented!"
        event.Skip()

    def btnDisable_handler(self, event):  # wxGlade: AdonsTree.<event_handler>
        print "Event handler 'btnDisable_handler' not implemented!"
        event.Skip()

    def btnOk_handler(self, event):  # wxGlade: AdonsTree.<event_handler>
        print "Event handler 'btnOk_handler' not implemented!"
        event.Skip()

    def btnCancel_handler(self, event):  # wxGlade: AdonsTree.<event_handler>
        print "Event handler 'btnCancel_handler' not implemented!"
        event.Skip()

# end of class AdonsTree
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    fmg_frame = (None, wx.ID_ANY, "")
    app.SetTopWindow(fmg_frame)
    fmg_frame.Show()
    app.MainLoop()