#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Wed Mar 12 22:02:43 2014

import wx
import wx.grid

# begin wxGlade: extracode
# end wxGlade


class LoaderFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LoaderFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.STAY_ON_TOP|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.listModules = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.LC_SINGLE_SEL|wx.SUNKEN_BORDER)
        self.btnLoadedModules = wx.Button(self, -1, u"Загруженные модули")
        self.btnUpdateModules = wx.Button(self, -1, u"Перезагрузить модули")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.listModules_on_activate, self.listModules)
        self.Bind(wx.EVT_BUTTON, self.btnLoadedModules_on_click, self.btnLoadedModules)
        self.Bind(wx.EVT_BUTTON, self.btnUpdateModules_on_click, self.btnUpdateModules)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LoaderFrame.__set_properties
        self.SetTitle(u"Компоненты модели")
        self.listModules.SetMinSize((360, 400))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LoaderFrame.__do_layout
        sizer_1 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(self.listModules, 1, wx.EXPAND|wx.FIXED_MINSIZE, 4)
        grid_sizer_1.Add(self.btnLoadedModules, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_1.Add(self.btnUpdateModules, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.AddGrowableRow(0)
        sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def btnLoadedModules_on_click(self, event): # wxGlade: LoaderFrame.<event_handler>
        print "Event handler `btnLoadedModules_on_click' not implemented"
        event.Skip()

    def btnUpdateModules_on_click(self, event): # wxGlade: LoaderFrame.<event_handler>
        print "Event handler `btnUpdateModules_on_click' not implemented"
        event.Skip()

    def listModules_on_activate(self, event): # wxGlade: LoaderFrame.<event_handler>
        print "Event handler `listModules_on_activate' not implemented"
        event.Skip()

# end of class LoaderFrame


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

    def on_cell_dclick(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler `on_cell_dclick' not implemented!"
        event.Skip()

    def on_loaded_modules(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler `on_loaded_modules' not implemented!"
        event.Skip()

    def on_update_modules(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler `on_update_modules' not implemented!"
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
